# base image
FROM 

# Run any terminal command 
RUN 

# Add an environment variable to your container
ENV

# NEEDED - sets the base directory in the container
WORKDIR

# Copies selected files from local machine onto container
COPY

# Like copy, but can download from external links
ADD

# Open specified port on container
EXPOSE


# Both of these define the command that is run when the container starts
CMD [ "" ]

ENTRYPOINT [ "executable" ]